# Cubix block1 optional homework
# Miskovits Dániel

# run after merging or pushing to main
# run the integration tests, build a JAR, and create and publish a Docker image based on that

name: Third complex workflow

on:
  push:
    branches:
    - main
    - 'ci/**'
  pull_request:
    branches:
      - main
      - 'ci/**'
    types:
      - closed

jobs:

  integrationtest:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Run integration tests
      run: ./mvnw clean integration-test
  
  maven-build:
    runs-on: ubuntu-latest
    needs: integrationtest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        cache: 'maven'
    - name: Build with Maven
      run: ./mvnw clean package verify
    - name: Upload artifact for docker-publish job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  docker-publish:
    runs-on: ubuntu-latest
    needs: maven-build
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Download artifact from maven-build job
      uses: actions/download-artifact@v3
      with:
        name: java-app
    - name: Logging in to Docker
      run: docker login ghcr.io -u miskovitsd -p ${{ github.token }}
    - name: Build the Docker image
      run: docker build . -t ghcr.io/miskovitsd/cubix/1/optional/app:springboot
    - name: Publishing the Docker image
      run: docker push ghcr.io/miskovitsd/cubix/1/optional/app:springboot
